[workspace]
authors = ["pedestrianlove <jsli@linux.com>"]
channels = ["conda-forge"]
name = "llm"
platforms = ["linux-64"]
version = "0.1.0"

[activation.env]
CUDA_HOME = "$CONDA_PREFIX"

[tasks]

[dependencies]
cuda = "12.9.*"
python = "3.14.*"
"llama.cpp" = ">=7880,<7881"

[pypi-dependencies]
sglang = ">=0.5.2, <0.6"
